# Ruby
# Package your Ruby application.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    gem install simplecov-json
    gem install simplecov -v 0.12.0
    gem install minitest
    
  displayName: 'instalando gems'

- script: ruby simplecov.rb
  displayName: 'ruby simplecov.rb'
